/**
 * Platform + Embed color system.
 * CONIS Design Manual SSOT — PR-022C.
 * Navy = identity. Blue = interaction. Green = success only.
 */
export const palette = {
  navy: '#001930',
  creamLight: '#F7F6F4',
  creamMid: '#E8E5E0',
  creamDark: '#D9D4CC',
  /** @deprecated Use creamLight — alias for Client Studio / Embed. */
  warmWhite: '#F7F6F4',
  /** @deprecated Use creamMid — alias for Client Studio / Embed. */
  warmGray: '#E8E5E0',
  lightGray: '#E3E3E3',
  gold: '#C8A165',
  goldIntense: '#B8922D',
  /** Premium badge surface — cream, never gold-tint panel. */
  goldSurface: '#F7F6F4',
  platformBg: '#F7F6F4',
  platformMuted: '#64748B',
  platformLine: '#E3E3E3',
  /**
   * Interaction blue (click-model / Manager mid blue).
   * Primary button, CTA, links, focus, active accents — never Green.
   */
  platformBlue: '#18428F',
  /** Active / info surface — Cream Dark (not blue fill). */
  platformBlueBg: '#D9D4CC',
  platformGreen: '#137A43',
  platformGreenBg: '#EAF5EE',
  platformRed: '#A93226',
  platformRedBg: '#F8EBE9',
  /** Warning — leave for later iteration; keep stable placeholders. */
  platformWarning: '#B45309',
  platformWarningBg: '#FFF4E5',
  platformSection: '#7D8796',
  pureWhite: '#FFFFFF',
} as const;

export const colors = {
  white: palette.creamLight,
  black: palette.navy,
  neutral: {
    50: palette.creamLight,
    100: palette.creamLight,
    200: palette.creamMid,
    300: palette.lightGray,
    400: palette.creamDark,
    500: palette.navy,
    600: palette.navy,
    700: palette.navy,
    800: palette.navy,
    900: palette.navy,
    950: palette.navy,
  },
  status: {
    pass: palette.platformGreen,
    passBg: palette.platformGreenBg,
    ready: palette.platformGreen,
    readyBg: palette.platformGreenBg,
    published: palette.platformGreen,
    publishedBg: palette.platformGreenBg,
    warning: palette.platformWarning,
    warningBg: palette.platformWarningBg,
    draft: palette.platformWarning,
    draftBg: palette.platformWarningBg,
    fail: palette.platformRed,
    failBg: palette.platformRedBg,
    error: palette.platformRed,
    errorBg: palette.platformRedBg,
    info: palette.platformBlue,
    infoBg: palette.creamDark,
    gold: palette.goldIntense,
    goldBg: palette.goldSurface,
  },
  background: {
    primary: palette.platformBg,
    secondary: palette.platformBg,
    tertiary: palette.creamMid,
  },
  foreground: {
    primary: palette.navy,
    secondary: palette.navy,
    tertiary: palette.platformMuted,
    muted: palette.platformMuted,
  },
  border: {
    default: palette.platformLine,
    strong: palette.platformLine,
    gold: palette.goldIntense,
  },
  brand: {
    navy: palette.navy,
    gold: palette.gold,
    goldIntense: palette.goldIntense,
    goldLight: palette.goldSurface,
    blue: palette.platformBlue,
  },
  action: {
    primary: palette.platformBlue,
    onPrimary: palette.pureWhite,
    secondary: palette.pureWhite,
    onSecondary: palette.navy,
    secondaryAccent: palette.navy,
    accent: palette.platformBlue,
    onAccent: palette.pureWhite,
    muted: palette.creamDark,
    onMuted: palette.platformMuted,
    danger: palette.platformRed,
    onDanger: palette.pureWhite,
    success: palette.platformGreen,
    onSuccess: palette.pureWhite,
  },
  surface: {
    chatUser: palette.creamMid,
    chatAssistant: palette.creamLight,
    chatIncoming: palette.creamMid,
    chatOutgoing: palette.creamLight,
    placeholder: palette.creamDark,
    card: palette.pureWhite,
    elevated: palette.pureWhite,
    inset: palette.creamMid,
    interactive: palette.creamMid,
  },
  platform: {
    navy: palette.navy,
    gold: palette.goldIntense,
    goldLight: palette.goldSurface,
    creamLight: palette.creamLight,
    creamMid: palette.creamMid,
    creamDark: palette.creamDark,
    bg: palette.platformBg,
    muted: palette.platformMuted,
    line: palette.platformLine,
    blue: palette.platformBlue,
    blueBg: palette.platformBlueBg,
    green: palette.platformGreen,
    greenBg: palette.platformGreenBg,
    red: palette.platformRed,
    redBg: palette.platformRedBg,
    warning: palette.platformWarning,
    warningBg: palette.platformWarningBg,
    section: palette.platformSection,
    card: palette.pureWhite,
  },
} as const;
