/**
 * Platform + Embed color system.
 * Click-model SSOT (`docs/platform/click model.html`) — no local studio variants.
 */
export const palette = {
  navy: '#001930',
  warmWhite: '#F7F6F4',
  warmGray: '#E8E5E0',
  lightGray: '#E3E3E3',
  gold: '#C8A165',
  goldIntense: '#B8922D',
  goldLight: '#FBF7EE',
  platformBg: '#F5F7FB',
  platformMuted: '#64748B',
  platformLine: '#E2E8F0',
  platformBlue: '#18428F',
  platformBlueBg: '#EEF4FF',
  platformGreen: '#138D45',
  platformGreenBg: '#E6F7ED',
  platformRed: '#DC2626',
  platformRedBg: '#FEF2F2',
  platformWarning: '#B45309',
  platformWarningBg: '#FFF4E5',
  platformSection: '#7D8796',
  pureWhite: '#FFFFFF',
} as const;

export const colors = {
  white: palette.warmWhite,
  black: palette.navy,
  neutral: {
    50: palette.warmWhite,
    100: palette.warmWhite,
    200: palette.lightGray,
    300: palette.lightGray,
    400: palette.lightGray,
    500: palette.navy,
    600: palette.navy,
    700: palette.navy,
    800: palette.navy,
    900: palette.navy,
    950: palette.navy,
  },
  /** Click-model status system — single visual vocabulary. */
  status: {
    pass: palette.platformGreen,
    passBg: palette.platformGreenBg,
    ready: palette.platformGreen,
    readyBg: palette.platformGreenBg,
    published: palette.platformGreen,
    publishedBg: palette.platformGreenBg,
    warning: palette.platformWarning,
    warningBg: palette.platformWarningBg,
    draft: palette.platformWarning,
    draftBg: palette.platformWarningBg,
    fail: palette.platformRed,
    failBg: palette.platformRedBg,
    error: palette.platformRed,
    errorBg: palette.platformRedBg,
    info: palette.platformBlue,
    infoBg: palette.platformBlueBg,
    gold: palette.goldIntense,
    goldBg: palette.goldLight,
  },
  background: {
    primary: palette.platformBg,
    secondary: palette.platformBg,
    tertiary: palette.lightGray,
  },
  foreground: {
    primary: palette.navy,
    secondary: palette.navy,
    tertiary: palette.platformMuted,
    muted: palette.platformMuted,
  },
  border: {
    default: palette.platformLine,
    strong: palette.platformLine,
    gold: palette.goldIntense,
  },
  brand: {
    navy: palette.navy,
    gold: palette.gold,
    goldIntense: palette.goldIntense,
    goldLight: palette.goldLight,
  },
  action: {
    primary: palette.navy,
    onPrimary: palette.pureWhite,
    secondary: palette.pureWhite,
    onSecondary: palette.navy,
    secondaryAccent: palette.gold,
    accent: palette.goldIntense,
    onAccent: palette.navy,
    muted: palette.lightGray,
    onMuted: palette.navy,
  },
  surface: {
    chatUser: palette.warmGray,
    chatAssistant: palette.warmWhite,
    chatIncoming: palette.warmGray,
    chatOutgoing: palette.warmWhite,
    placeholder: palette.lightGray,
    card: palette.pureWhite,
    elevated: palette.pureWhite,
    inset: palette.lightGray,
    interactive: palette.warmGray,
  },
  platform: {
    navy: palette.navy,
    gold: palette.goldIntense,
    goldLight: palette.goldLight,
    bg: palette.platformBg,
    muted: palette.platformMuted,
    line: palette.platformLine,
    blue: palette.platformBlue,
    blueBg: palette.platformBlueBg,
    green: palette.platformGreen,
    greenBg: palette.platformGreenBg,
    red: palette.platformRed,
    redBg: palette.platformRedBg,
    warning: palette.platformWarning,
    warningBg: palette.platformWarningBg,
    section: palette.platformSection,
    card: palette.pureWhite,
  },
} as const;
