import type { CapabilityDefinition } from '../domain/types';

/**
 * Canonical Capability Registry definitions — each capability exists once.
 * Entitlement (BX-21/22) is commercial classification; Registry remains SSOT.
 */
export const CAPABILITY_DEFINITIONS: readonly CapabilityDefinition[] = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['builder'],
    dependencies: [],
    maturity: 'stable',
    entitlement: 'included',
    description: 'Project overview and readiness summary.',
  },
  {
    id: 'media',
    name: 'Media',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['builder'],
    dependencies: ['dashboard'],
    maturity: 'stable',
    entitlement: 'included',
    description: 'Media Studio over House Package content areas.',
  },
  {
    id: 'knowledge',
    name: 'Knowledge',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['builder'],
    dependencies: ['dashboard'],
    maturity: 'stable',
    entitlement: 'included',
    description: 'Knowledge Composer projection and editing surfaces.',
  },
  {
    id: 'experience',
    name: 'Experience',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['builder', 'sales'],
    dependencies: ['dashboard'],
    maturity: 'stable',
    entitlement: 'included',
    description: 'Experience Composer — Decision Experience structure.',
  },
  {
    id: 'preview',
    name: 'Preview',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['builder'],
    dependencies: ['experience', 'media'],
    maturity: 'stable',
    entitlement: 'included',
    description: 'Preview Center — personas, devices, Decision Path.',
  },
  {
    id: 'release',
    name: 'Release',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['builder'],
    dependencies: ['experience', 'media', 'knowledge'],
    maturity: 'stable',
    entitlement: 'included',
    description: 'Release Center — publish orchestration metadata.',
  },
  {
    id: 'collaboration',
    name: 'Collaboration',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['builder', 'manager'],
    dependencies: ['dashboard'],
    maturity: 'beta',
    entitlement: 'optional',
    description: 'Collaboration workspace — review, tasks, activity.',
  },
  {
    id: 'intelligence',
    name: 'Intelligence',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['builder', 'manager', 'sales'],
    dependencies: [],
    maturity: 'stable',
    entitlement: 'included',
    description: 'Decision Intelligence Core client surface.',
  },
  {
    id: 'ai',
    name: 'AI Author',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['builder'],
    dependencies: ['experience', 'knowledge', 'media', 'release'],
    maturity: 'beta',
    entitlement: 'optional',
    description: 'Contextual AI Author suggestions (deterministic proposals).',
  },
  {
    id: 'operations',
    name: 'Operations',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['manager'],
    dependencies: ['intelligence'],
    maturity: 'beta',
    entitlement: 'optional',
    description: 'Manager Operations Terminal surfaces.',
  },
  {
    id: 'pipeline',
    name: 'Pipeline',
    version: '0.1.0',
    owner: 'platform',
    studioSupport: ['sales'],
    dependencies: ['intelligence', 'experience'],
    maturity: 'experimental',
    entitlement: 'hidden',
    description: 'Sales pipeline placeholder — commercially hidden until productized.',
  },
  {
    id: 'customer-success',
    name: 'Customer Success',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['manager', 'sales', 'builder'],
    dependencies: [],
    maturity: 'beta',
    entitlement: 'optional',
    description:
      'Customer Success Platform — onboarding, adoption, health, recommendations.',
  },
  {
    id: 'operations-center',
    name: 'Platform Operations Center',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['manager'],
    dependencies: ['customer-success'],
    maturity: 'beta',
    entitlement: 'optional',
    description:
      'Platform Operations Center — CONIS platform ops overview, timeline, alerts, metrics.',
  },
  {
    id: 'product-learning',
    name: 'Product Learning',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['manager'],
    dependencies: [],
    maturity: 'beta',
    entitlement: 'optional',
    description:
      'Product Learning Center — feedback registry, insights, roadmap suggestions.',
  },
  {
    id: 'commercial-platform',
    name: 'Commercial Platform',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['manager'],
    dependencies: [],
    maturity: 'beta',
    entitlement: 'included',
    description:
      'Commercial Platform — editions, entitlements, subscriptions, upgrade suggestions (no billing).',
  },
  {
    id: 'launch-center',
    name: 'Launch Center',
    version: '1.0.0',
    owner: 'platform',
    studioSupport: ['manager'],
    dependencies: [],
    maturity: 'beta',
    entitlement: 'included',
    description:
      'CONIS Launch Center — Pilot → GA orchestration over existing readiness projections.',
  },
] as const;
