import { AppShell } from '../../components/layout/AppShell';
import { BuilderHeader } from '../../components/shell/BuilderHeader';
import { BuilderSidebar } from '../../components/shell/BuilderSidebar';
import { PublishPanel } from '../../components/shell/PublishPanel';
import { WorkspaceCanvas } from '../../components/shell/WorkspaceCanvas';
import { useBuilderStudioSession } from './useBuilderStudioSession';

export function BuilderStudioApp() {
  const session = useBuilderStudioSession();

  return (
    <AppShell
      header={<BuilderHeader partnerName={session.workspace.partner.name} />}
      sidebar={
        <BuilderSidebar
          partner={session.workspace.partner}
          projects={session.workspace.projects}
          activeProjectId={session.workspace.activeProjectId}
          onOpenProject={session.openProject}
          onCreateProject={session.createProject}
        />
      }
      publishPanel={
        <PublishPanel
          pipeline={session.pipeline}
          latestBuild={session.latestBuild}
          buildHistory={session.buildHistory}
          latestPublish={session.latestPublish}
          publishHistory={session.publishHistory}
          preview={session.preview}
          previewHistory={session.previewHistory}
          validationReport={session.validationReport}
          validationHistory={session.validationHistory}
          validationEvents={session.validationEvents}
          onValidateProject={session.validateProject}
          onBuildProject={session.buildProject}
          onPublishPackage={session.publishPackage}
          onOpenPreview={session.openPreview}
          onRefreshPreview={session.refreshPreview}
          onClosePreview={session.closePreview}
        />
      }
    >
      <WorkspaceCanvas
        projectModel={session.activeProjectModel}
        objectPackage={session.objectPackage}
        experience={session.experience}
        experienceStructure={session.experienceStructure}
        composerEvents={session.composerEvents}
        selectedSceneId={session.selectedSceneId}
        knowledgePackage={session.knowledgePackage}
        knowledgeEvents={session.knowledgeEvents}
        decisionKnowledge={session.decisionKnowledge}
        decisionEvents={session.decisionEvents}
        aiContext={session.aiContext}
        contextEvents={session.contextEvents}
        knowledgeLayerRegistry={session.knowledgeLayerRegistry}
        knowledgeLayerBundle={session.knowledgeLayerBundle}
        knowledgeLayerEvents={session.knowledgeLayerEvents}
        knowledgeReferences={session.knowledgeReferences}
        resolvedLayers={session.resolvedLayers}
        learningPackage={session.learningPackage}
        learningEvents={session.learningEvents}
        learningOrigins={session.learningOrigins}
        decisionModel={session.decisionModel}
        decisionEngineEvents={session.decisionEngineEvents}
        runtimeModel={session.runtimeModel}
        decisionRuntimeEvents={session.decisionRuntimeEvents}
        evaluationResult={session.evaluationResult}
        evaluationEvents={session.evaluationEvents}
        evaluationValidationMessage={session.evaluationValidationMessage}
        decisionStory={session.decisionStory}
        storyEvents={session.storyEvents}
        storyMessage={session.storyMessage}
        runtimeSession={session.runtimeSession}
        sessionEvents={session.sessionEvents}
        sessionMessage={session.sessionMessage}
        behaviorEvaluation={session.behaviorEvaluation}
        behaviorSignals={session.behaviorSignals}
        behaviorEvents={session.behaviorEvents}
        behaviorMessage={session.behaviorMessage}
        analyticsSnapshot={session.analyticsSnapshot}
        analyticsEvents={session.analyticsEvents}
        analyticsMessage={session.analyticsMessage}
        learningRecord={session.learningRecord}
        learningValidation={session.learningValidation}
        learningImportReport={session.learningImportReport}
        learningExportPayload={session.learningExportPayload}
        learningPipelineEvents={session.learningPipelineEvents}
        learningPipelineMessage={session.learningPipelineMessage}
        learningRecordsPackage={session.learningRecordsPackage}
        learningPackageManagerEvents={session.learningPackageManagerEvents}
        learningPackageIndexCount={session.learningPackageIndexCount}
        learningPackageManagerMessage={session.learningPackageManagerMessage}
        patternCollection={session.patternCollection}
        patternExtractionEvents={session.patternExtractionEvents}
        patternIndexCount={session.patternIndexCount}
        patternExtractionMessage={session.patternExtractionMessage}
        patternCatalog={session.patternCatalog}
        patternIntelligenceEvents={session.patternIntelligenceEvents}
        patternIntelligenceIndexCount={session.patternIntelligenceIndexCount}
        patternIntelligenceMessage={session.patternIntelligenceMessage}
        heuristicCatalog={session.heuristicCatalog}
        heuristicEngineEvents={session.heuristicEngineEvents}
        heuristicIndexCount={session.heuristicIndexCount}
        heuristicEngineMessage={session.heuristicEngineMessage}
        synthesizedKnowledgeBase={session.synthesizedKnowledgeBase}
        knowledgeSynthesisEvents={session.knowledgeSynthesisEvents}
        knowledgeSynthesisIndexCount={session.knowledgeSynthesisIndexCount}
        knowledgeSynthesisMessage={session.knowledgeSynthesisMessage}
        gatewayAIContextPackage={session.gatewayAIContextPackage}
        aiDecisionGatewayEvents={session.aiDecisionGatewayEvents}
        aiDecisionGatewayIndexCount={session.aiDecisionGatewayIndexCount}
        aiDecisionGatewayMessage={session.aiDecisionGatewayMessage}
        personalizationPackage={session.personalizationPackage}
        personalizationEngineEvents={session.personalizationEngineEvents}
        personalizationIndexCount={session.personalizationIndexCount}
        personalizationEngineMessage={session.personalizationEngineMessage}
        personalizedContextPackage={session.personalizedContextPackage}
        personalizationRuntimeEvents={session.personalizationRuntimeEvents}
        personalizationRuntimeIndexCount={
          session.personalizationRuntimeIndexCount
        }
        personalizationRuntimeMessage={session.personalizationRuntimeMessage}
        decisionExecutionPackage={session.decisionExecutionPackage}
        decisionOrchestratorEvents={session.decisionOrchestratorEvents}
        decisionOrchestratorIndexCount={session.decisionOrchestratorIndexCount}
        decisionOrchestratorMessage={session.decisionOrchestratorMessage}
        runtimeExecutionPackage={session.runtimeExecutionPackage}
        experienceRuntimeEvents={session.experienceRuntimeEvents}
        experienceRuntimeIndexCount={session.experienceRuntimeIndexCount}
        experienceRuntimeMessage={session.experienceRuntimeMessage}
        experienceModulePackage={session.experienceModulePackage}
        moduleCoordinatorEvents={session.moduleCoordinatorEvents}
        moduleCoordinatorIndexCount={session.moduleCoordinatorIndexCount}
        moduleCoordinatorMessage={session.moduleCoordinatorMessage}
        experienceStatePackage={session.experienceStatePackage}
        experienceStateEvents={session.experienceStateEvents}
        experienceStateIndexCount={session.experienceStateIndexCount}
        experienceStateMessage={session.experienceStateMessage}
        observabilityPackage={session.observabilityPackage}
        observabilityEvents={session.observabilityEvents}
        observabilityIndexCount={session.observabilityIndexCount}
        observabilityMessage={session.observabilityMessage}
        runtimeHealthPackage={session.runtimeHealthPackage}
        runtimeHealthEvents={session.runtimeHealthEvents}
        runtimeHealthIndexCount={session.runtimeHealthIndexCount}
        runtimeHealthMessage={session.runtimeHealthMessage}
        runtimeAuditPackage={session.runtimeAuditPackage}
        runtimeAuditEvents={session.runtimeAuditEvents}
        runtimeAuditIndexCount={session.runtimeAuditIndexCount}
        runtimeAuditMessage={session.runtimeAuditMessage}
        runtimeGovernancePackage={session.runtimeGovernancePackage}
        runtimeGovernanceEvents={session.runtimeGovernanceEvents}
        runtimeGovernanceIndexCount={session.runtimeGovernanceIndexCount}
        runtimeGovernanceMessage={session.runtimeGovernanceMessage}
        runtimePolicyPackage={session.runtimePolicyPackage}
        runtimePolicyEvents={session.runtimePolicyEvents}
        runtimePolicyIndexCount={session.runtimePolicyIndexCount}
        runtimePolicyMessage={session.runtimePolicyMessage}
        runtimeEnforcementPackage={session.runtimeEnforcementPackage}
        runtimeEnforcementEvents={session.runtimeEnforcementEvents}
        runtimeEnforcementIndexCount={session.runtimeEnforcementIndexCount}
        runtimeEnforcementMessage={session.runtimeEnforcementMessage}
        runtimeResiliencePackage={session.runtimeResiliencePackage}
        runtimeResilienceEvents={session.runtimeResilienceEvents}
        runtimeResilienceIndexCount={session.runtimeResilienceIndexCount}
        runtimeResilienceMessage={session.runtimeResilienceMessage}
        runtimeRecoveryPackage={session.runtimeRecoveryPackage}
        runtimeRecoveryEvents={session.runtimeRecoveryEvents}
        runtimeRecoveryIndexCount={session.runtimeRecoveryIndexCount}
        runtimeRecoveryMessage={session.runtimeRecoveryMessage}
        runtimeRecoveryExecutionPackage={session.runtimeRecoveryExecutionPackage}
        runtimeRecoveryExecutionEvents={session.runtimeRecoveryExecutionEvents}
        runtimeRecoveryExecutionIndexCount={
          session.runtimeRecoveryExecutionIndexCount
        }
        runtimeRecoveryExecutionMessage={session.runtimeRecoveryExecutionMessage}
        runtimeRecoveryCoordinatorPackage={
          session.runtimeRecoveryCoordinatorPackage
        }
        runtimeRecoveryCoordinatorEvents={
          session.runtimeRecoveryCoordinatorEvents
        }
        runtimeRecoveryCoordinatorIndexCount={
          session.runtimeRecoveryCoordinatorIndexCount
        }
        runtimeRecoveryCoordinatorMessage={
          session.runtimeRecoveryCoordinatorMessage
        }
        runtimeRecoveryReportingPackage={
          session.runtimeRecoveryReportingPackage
        }
        runtimeRecoveryReportingEvents={session.runtimeRecoveryReportingEvents}
        runtimeRecoveryReportingIndexCount={
          session.runtimeRecoveryReportingIndexCount
        }
        runtimeRecoveryReportingMessage={
          session.runtimeRecoveryReportingMessage
        }
        runtimeOperationsPackage={session.runtimeOperationsPackage}
        runtimeOperationsEvents={session.runtimeOperationsEvents}
        runtimeOperationsIndexCount={session.runtimeOperationsIndexCount}
        runtimeOperationsMessage={session.runtimeOperationsMessage}
        runtimeIntegrationPackage={session.runtimeIntegrationPackage}
        runtimeIntegrationEvents={session.runtimeIntegrationEvents}
        runtimeIntegrationIndexCount={session.runtimeIntegrationIndexCount}
        runtimeIntegrationMessage={session.runtimeIntegrationMessage}
        runtimeRegistryPackage={session.runtimeRegistryPackage}
        runtimeRegistryEvents={session.runtimeRegistryEvents}
        runtimeRegistryIndexCount={session.runtimeRegistryIndexCount}
        runtimeRegistryMessage={session.runtimeRegistryMessage}
        runtimeManifestPackage={session.runtimeManifestPackage}
        runtimeManifestEvents={session.runtimeManifestEvents}
        runtimeManifestIndexCount={session.runtimeManifestIndexCount}
        runtimeManifestMessage={session.runtimeManifestMessage}
        runtimeApiPackage={session.runtimeApiPackage}
        runtimeApiEvents={session.runtimeApiEvents}
        runtimeApiIndexCount={session.runtimeApiIndexCount}
        runtimeApiMessage={session.runtimeApiMessage}
        runtimeCompatibilityPackage={session.runtimeCompatibilityPackage}
        runtimeCompatibilityEvents={session.runtimeCompatibilityEvents}
        runtimeCompatibilityIndexCount={
          session.runtimeCompatibilityIndexCount
        }
        runtimeCompatibilityMessage={session.runtimeCompatibilityMessage}
        runtimeContractPackage={session.runtimeContractPackage}
        runtimeContractEvents={session.runtimeContractEvents}
        runtimeContractIndexCount={session.runtimeContractIndexCount}
        runtimeContractMessage={session.runtimeContractMessage}
        runtimeExtensionPackage={session.runtimeExtensionPackage}
        runtimeExtensionEvents={session.runtimeExtensionEvents}
        runtimeExtensionIndexCount={session.runtimeExtensionIndexCount}
        runtimeExtensionMessage={session.runtimeExtensionMessage}
        objectPublicationPackage={session.objectPublicationPackage}
        objectPublicationEvents={session.objectPublicationEvents}
        objectPublicationIndexCount={session.objectPublicationIndexCount}
        objectPublicationMessage={session.objectPublicationMessage}
        publishedObjectPackage={session.publishedObjectPackage}
        publishedObjectEvents={session.publishedObjectEvents}
        publishedObjectIndexCount={session.publishedObjectIndexCount}
        publishedObjectMessage={session.publishedObjectMessage}
        platformPublicationPackage={session.platformPublicationPackage}
        platformPublicationEvents={session.platformPublicationEvents}
        platformPublicationIndexCount={session.platformPublicationIndexCount}
        platformPublicationMessage={session.platformPublicationMessage}
        clientPublicationPackage={session.clientPublicationPackage}
        clientPublicationEvents={session.clientPublicationEvents}
        clientPublicationIndexCount={session.clientPublicationIndexCount}
        clientPublicationMessage={session.clientPublicationMessage}
        publicationReadinessPackage={session.publicationReadinessPackage}
        publicationReadinessEvents={session.publicationReadinessEvents}
        publicationReadinessIndexCount={session.publicationReadinessIndexCount}
        publicationReadinessMessage={session.publicationReadinessMessage}
        runtimeBootstrapPackage={session.runtimeBootstrapPackage}
        runtimeBootstrapEvents={session.runtimeBootstrapEvents}
        runtimeBootstrapIndexCount={session.runtimeBootstrapIndexCount}
        runtimeBootstrapMessage={session.runtimeBootstrapMessage}
        artifactVersionPackage={session.artifactVersionPackage}
        artifactVersionEvents={session.artifactVersionEvents}
        artifactVersionIndexCount={session.artifactVersionIndexCount}
        artifactVersionMessage={session.artifactVersionMessage}
        artifactDependencyPackage={session.artifactDependencyPackage}
        artifactDependencyEvents={session.artifactDependencyEvents}
        artifactDependencyIndexCount={session.artifactDependencyIndexCount}
        artifactDependencyMessage={session.artifactDependencyMessage}
        publicationPlanPackage={session.publicationPlanPackage}
        publicationPlanEvents={session.publicationPlanEvents}
        publicationPlanIndexCount={session.publicationPlanIndexCount}
        publicationPlanMessage={session.publicationPlanMessage}
        publicationExecutionPackage={session.publicationExecutionPackage}
        publicationExecutionEvents={session.publicationExecutionEvents}
        publicationExecutionIndexCount={session.publicationExecutionIndexCount}
        publicationExecutionMessage={session.publicationExecutionMessage}
        artifactExportPackage={session.artifactExportPackage}
        artifactExportEvents={session.artifactExportEvents}
        artifactExportIndexCount={session.artifactExportIndexCount}
        artifactExportMessage={session.artifactExportMessage}
        priorityRegistry={session.priorityRegistry}
        moduleRegistry={session.moduleRegistry}
        objectEvents={session.objectEvents}
        validationReport={session.validationReport}
        manifest={session.projectManifest}
        versions={session.versions}
        readiness={session.readiness}
        timeline={session.timeline}
        activeSection={session.activeSection}
        onSelectSection={session.selectSection}
        onAddAsset={session.addAsset}
        onRemoveAsset={session.removeAsset}
        onUpdateMetadata={session.updateAssetMetadata}
        onUpdateObjectMetadata={session.updateObjectMetadata}
        onToggleModule={session.toggleObjectModule}
        onSaveObject={session.saveObject}
        onDuplicateObject={session.duplicateObject}
        onSelectScene={session.selectScene}
        onAddScene={session.addScene}
        onRenameScene={session.renameScene}
        onMoveScene={session.moveScene}
        onRemoveScene={session.removeScene}
        onToggleSceneModule={session.toggleSceneModule}
        onSaveKnowledge={session.saveKnowledge}
        onAddFact={session.addFact}
        onAddEntity={session.addEntity}
        onAddRelationship={session.addRelationship}
        onAddFaq={session.addFaq}
        onSaveDecision={session.saveDecisionKnowledge}
        onAddDecisionRule={session.addDecisionRule}
        onAddDecisionSignal={session.addDecisionSignal}
        onAddDecisionStrategy={session.addDecisionStrategy}
        onToggleDecisionPriority={session.toggleDecisionPriority}
        onBuildContext={session.buildAIContext}
        onRefreshContext={session.refreshAIContext}
        onClearContext={session.clearAIContext}
        onEnsureKnowledgeLayers={session.ensureKnowledgeLayers}
        onAddDemoLayerReferences={session.addDemoLayerReferences}
        onRemoveLayerReference={session.removeLayerReference}
        onSaveLearning={session.saveLearning}
        onAddLearningObservation={session.addLearningObservation}
        onAddLearningPattern={session.addLearningPattern}
        onAddLearningHeuristic={session.addLearningHeuristic}
        onBuildDecisionModel={session.buildDecisionModel}
        onValidateDecisionModel={session.validateDecisionModel}
        onDisposeDecisionModel={session.disposeDecisionModel}
        onCreateDecisionRuntime={session.createDecisionRuntime}
        onValidateDecisionRuntime={session.validateDecisionRuntime}
        onDisposeDecisionRuntime={session.disposeDecisionRuntime}
        onEvaluateRules={session.evaluateRules}
        onValidateEvaluation={session.validateEvaluation}
        onDisposeEvaluation={session.disposeEvaluation}
        onComposeStory={session.composeStory}
        onValidateStory={session.validateStory}
        onDisposeStory={session.disposeStory}
        onCreateRuntimeSession={session.createRuntimeSession}
        onStartRuntimeSession={session.startRuntimeSession}
        onNextSessionMove={session.nextSessionMove}
        onPreviousSessionMove={session.previousSessionMove}
        onCompleteRuntimeSession={session.completeRuntimeSession}
        onDisposeRuntimeSession={session.disposeRuntimeSession}
        onEvaluateBehavior={session.evaluateBehavior}
        onReceiveDemoBehaviorSignals={session.receiveDemoBehaviorSignals}
        onDisposeBehavior={session.disposeBehavior}
        onRecordAnalytics={session.recordAnalytics}
        onAggregateAnalytics={session.aggregateAnalytics}
        onExportAnalytics={session.exportAnalytics}
        onDisposeAnalytics={session.disposeAnalytics}
        onImportLearning={session.importLearning}
        onValidateLearning={session.validateLearningPipeline}
        onAnonymizeLearning={session.anonymizeLearning}
        onTransformLearning={session.transformLearning}
        onDisposeLearningPipeline={session.disposeLearningPipeline}
        onCreateLearningRecordsPackage={session.createLearningRecordsPackage}
        onAddLearningRecordRef={session.addLearningRecordRef}
        onRemoveLastLearningRecordRef={session.removeLastLearningRecordRef}
        onValidateLearningRecordsPackage={session.validateLearningRecordsPackage}
        onPublishLearningRecordsPackage={session.publishLearningRecordsPackage}
        onDisposeLearningRecordsPackage={session.disposeLearningRecordsPackage}
        onExtractPatterns={session.extractPatterns}
        onValidatePatterns={session.validatePatterns}
        onPublishPatterns={session.publishPatterns}
        onDisposePatterns={session.disposePatterns}
        onExtractIntelligencePatterns={session.extractIntelligencePatterns}
        onMergeIntelligencePatterns={session.mergeIntelligencePatterns}
        onValidateIntelligencePatterns={session.validateIntelligencePatterns}
        onPublishIntelligencePatterns={session.publishIntelligencePatterns}
        onDisposeIntelligencePatterns={session.disposeIntelligencePatterns}
        onDeriveHeuristics={session.deriveHeuristics}
        onValidateHeuristics={session.validateHeuristics}
        onPublishHeuristics={session.publishHeuristics}
        onDisposeHeuristics={session.disposeHeuristics}
        onSynthesizeKnowledge={session.synthesizeKnowledge}
        onMergeKnowledge={session.mergeKnowledge}
        onValidateSynthesizedKnowledge={session.validateSynthesizedKnowledge}
        onPublishSynthesizedKnowledge={session.publishSynthesizedKnowledge}
        onDisposeSynthesizedKnowledge={session.disposeSynthesizedKnowledge}
        onBuildGatewayAIContext={session.buildGatewayAIContext}
        onFilterGatewayAIContext={session.filterGatewayAIContext}
        onValidateGatewayAIContext={session.validateGatewayAIContext}
        onPublishGatewayAIContext={session.publishGatewayAIContext}
        onDisposeGatewayAIContext={session.disposeGatewayAIContext}
        onPersonalizeContext={session.personalizeContext}
        onRankPersonalization={session.rankPersonalization}
        onValidatePersonalization={session.validatePersonalization}
        onPublishPersonalization={session.publishPersonalization}
        onDisposePersonalization={session.disposePersonalization}
        onProjectDecisionContext={session.projectDecisionContext}
        onRankDecisionContext={session.rankDecisionContext}
        onValidateDecisionContext={session.validateDecisionContext}
        onPublishDecisionContext={session.publishDecisionContext}
        onDisposeDecisionContext={session.disposeDecisionContext}
        onStartDecisionExecution={session.startDecisionExecution}
        onAdvanceDecisionExecution={session.advanceDecisionExecution}
        onTransitionDecisionExecution={session.transitionDecisionExecution}
        onCompleteDecisionExecution={session.completeDecisionExecution}
        onValidateDecisionExecution={session.validateDecisionExecution}
        onDisposeDecisionExecution={session.disposeDecisionExecution}
        onStartExperienceRuntime={session.startExperienceRuntime}
        onNextExperienceRuntimeMove={session.nextExperienceRuntimeMove}
        onPreviousExperienceRuntimeMove={session.previousExperienceRuntimeMove}
        onJumpExperienceRuntimeMove={session.jumpExperienceRuntimeMove}
        onCompleteExperienceRuntime={session.completeExperienceRuntime}
        onValidateExperienceRuntime={session.validateExperienceRuntime}
        onDisposeExperienceRuntime={session.disposeExperienceRuntime}
        onInitializeExperienceModules={session.initializeExperienceModules}
        onActivateExperienceModule={session.activateExperienceModule}
        onTransitionExperienceModule={session.transitionExperienceModule}
        onCompleteExperienceModules={session.completeExperienceModules}
        onValidateExperienceModules={session.validateExperienceModules}
        onDisposeExperienceModules={session.disposeExperienceModules}
        onCreateExperienceState={session.createExperienceState}
        onUpdateExperienceState={session.updateExperienceState}
        onCheckpointExperienceState={session.checkpointExperienceState}
        onRestoreExperienceState={session.restoreExperienceState}
        onCompleteExperienceState={session.completeExperienceState}
        onValidateExperienceState={session.validateExperienceState}
        onDisposeExperienceState={session.disposeExperienceState}
        onCollectRuntimeObservability={session.collectRuntimeObservability}
        onPublishRuntimeObservability={session.publishRuntimeObservability}
        onValidateRuntimeObservability={session.validateRuntimeObservability}
        onDisposeRuntimeObservability={session.disposeRuntimeObservability}
        onInspectRuntimeHealth={session.inspectRuntimeHealth}
        onPublishRuntimeHealth={session.publishRuntimeHealth}
        onValidateRuntimeHealth={session.validateRuntimeHealth}
        onDisposeRuntimeHealth={session.disposeRuntimeHealth}
        onRecordRuntimeAudit={session.recordRuntimeAudit}
        onPublishRuntimeAudit={session.publishRuntimeAudit}
        onValidateRuntimeAudit={session.validateRuntimeAudit}
        onDisposeRuntimeAudit={session.disposeRuntimeAudit}
        onEvaluateRuntimeGovernance={session.evaluateRuntimeGovernance}
        onPublishRuntimeGovernance={session.publishRuntimeGovernance}
        onValidateRuntimeGovernance={session.validateRuntimeGovernance}
        onDisposeRuntimeGovernance={session.disposeRuntimeGovernance}
        onInitializeRuntimePolicies={session.initializeRuntimePolicies}
        onRegisterRuntimePolicy={session.registerRuntimePolicy}
        onPublishRuntimePolicies={session.publishRuntimePolicies}
        onValidateRuntimePolicies={session.validateRuntimePolicies}
        onDisposeRuntimePolicies={session.disposeRuntimePolicies}
        onEvaluateRuntimeEnforcement={session.evaluateRuntimeEnforcement}
        onPublishRuntimeEnforcement={session.publishRuntimeEnforcement}
        onValidateRuntimeEnforcement={session.validateRuntimeEnforcement}
        onDisposeRuntimeEnforcement={session.disposeRuntimeEnforcement}
        onEvaluateRuntimeResilience={session.evaluateRuntimeResilience}
        onPublishRuntimeResilience={session.publishRuntimeResilience}
        onValidateRuntimeResilience={session.validateRuntimeResilience}
        onDisposeRuntimeResilience={session.disposeRuntimeResilience}
        onBuildRuntimeRecovery={session.buildRuntimeRecovery}
        onPublishRuntimeRecovery={session.publishRuntimeRecovery}
        onValidateRuntimeRecovery={session.validateRuntimeRecovery}
        onDisposeRuntimeRecovery={session.disposeRuntimeRecovery}
        onExecuteRuntimeRecoveryExecution={
          session.executeRuntimeRecoveryExecution
        }
        onPauseRuntimeRecoveryExecution={session.pauseRuntimeRecoveryExecution}
        onResumeRuntimeRecoveryExecution={
          session.resumeRuntimeRecoveryExecution
        }
        onValidateRuntimeRecoveryExecution={
          session.validateRuntimeRecoveryExecution
        }
        onPublishRuntimeRecoveryExecution={
          session.publishRuntimeRecoveryExecution
        }
        onDisposeRuntimeRecoveryExecution={
          session.disposeRuntimeRecoveryExecution
        }
        onStartRuntimeRecoveryCoordinator={
          session.startRuntimeRecoveryCoordinator
        }
        onCompleteRuntimeRecoveryCoordinator={
          session.completeRuntimeRecoveryCoordinator
        }
        onPublishRuntimeRecoveryCoordinator={
          session.publishRuntimeRecoveryCoordinator
        }
        onValidateRuntimeRecoveryCoordinator={
          session.validateRuntimeRecoveryCoordinator
        }
        onDisposeRuntimeRecoveryCoordinator={
          session.disposeRuntimeRecoveryCoordinator
        }
        onGenerateRuntimeRecoveryReporting={
          session.generateRuntimeRecoveryReporting
        }
        onPublishRuntimeRecoveryReporting={
          session.publishRuntimeRecoveryReporting
        }
        onValidateRuntimeRecoveryReporting={
          session.validateRuntimeRecoveryReporting
        }
        onDisposeRuntimeRecoveryReporting={
          session.disposeRuntimeRecoveryReporting
        }
        onCollectRuntimeOperations={session.collectRuntimeOperations}
        onPublishRuntimeOperations={session.publishRuntimeOperations}
        onValidateRuntimeOperations={session.validateRuntimeOperations}
        onDisposeRuntimeOperations={session.disposeRuntimeOperations}
        onRegisterRuntimeIntegration={session.registerRuntimeIntegration}
        onPublishRuntimeIntegration={session.publishRuntimeIntegration}
        onValidateRuntimeIntegration={session.validateRuntimeIntegration}
        onDisposeRuntimeIntegration={session.disposeRuntimeIntegration}
        onRegisterRuntimeRegistry={session.registerRuntimeRegistry}
        onPublishRuntimeRegistry={session.publishRuntimeRegistry}
        onValidateRuntimeRegistry={session.validateRuntimeRegistry}
        onDisposeRuntimeRegistry={session.disposeRuntimeRegistry}
        onGenerateRuntimeManifest={session.generateRuntimeManifest}
        onPublishRuntimeManifest={session.publishRuntimeManifest}
        onValidateRuntimeManifest={session.validateRuntimeManifest}
        onDisposeRuntimeManifest={session.disposeRuntimeManifest}
        onRegisterRuntimeApi={session.registerRuntimeApi}
        onPublishRuntimeApi={session.publishRuntimeApi}
        onValidateRuntimeApi={session.validateRuntimeApi}
        onDisposeRuntimeApi={session.disposeRuntimeApi}
        onRegisterRuntimeCompatibility={session.registerRuntimeCompatibility}
        onEvaluateRuntimeCompatibility={session.evaluateRuntimeCompatibility}
        onPublishRuntimeCompatibility={session.publishRuntimeCompatibility}
        onValidateRuntimeCompatibility={session.validateRuntimeCompatibility}
        onDisposeRuntimeCompatibility={session.disposeRuntimeCompatibility}
        onRegisterRuntimeContracts={session.registerRuntimeContracts}
        onPublishRuntimeContracts={session.publishRuntimeContracts}
        onValidateRuntimeContracts={session.validateRuntimeContracts}
        onDisposeRuntimeContracts={session.disposeRuntimeContracts}
        onRegisterRuntimeExtensions={session.registerRuntimeExtensions}
        onEnableRuntimeExtensions={session.enableRuntimeExtensions}
        onDisableRuntimeExtensions={session.disableRuntimeExtensions}
        onPublishRuntimeExtensions={session.publishRuntimeExtensions}
        onValidateRuntimeExtensions={session.validateRuntimeExtensions}
        onDisposeRuntimeExtensions={session.disposeRuntimeExtensions}
        onBuildObjectPublication={session.buildObjectPublication}
        onValidateObjectPublication={session.validateObjectPublication}
        onPublishObjectPublication={session.publishObjectPublication}
        onDisposeObjectPublication={session.disposeObjectPublication}
        onRegisterPublishedObjects={session.registerPublishedObjects}
        onArchivePublishedObjects={session.archivePublishedObjects}
        onValidatePublishedObjects={session.validatePublishedObjects}
        onDisposePublishedObjects={session.disposePublishedObjects}
        onRegisterPlatformPublications={session.registerPlatformPublications}
        onRefreshPlatformPublications={session.refreshPlatformPublications}
        onValidatePlatformPublications={session.validatePlatformPublications}
        onDisposePlatformPublications={session.disposePlatformPublications}
        onLoadClientPublication={session.loadClientPublication}
        onTransformClientPublication={session.transformClientPublication}
        onPublishClientPublication={session.publishClientPublication}
        onValidateClientPublication={session.validateClientPublication}
        onDisposeClientPublication={session.disposeClientPublication}
        onValidatePublicationReadiness={session.validatePublicationReadiness}
        onEvaluatePublicationReadiness={session.evaluatePublicationReadiness}
        onPublishPublicationReadiness={session.publishPublicationReadiness}
        onDisposePublicationReadiness={session.disposePublicationReadiness}
        onBuildRuntimeBootstrap={session.buildRuntimeBootstrap}
        onValidateRuntimeBootstrap={session.validateRuntimeBootstrap}
        onPublishRuntimeBootstrap={session.publishRuntimeBootstrap}
        onDisposeRuntimeBootstrap={session.disposeRuntimeBootstrap}
        onRegisterArtifactVersion={session.registerArtifactVersion}
        onActivateArtifactVersion={session.activateArtifactVersion}
        onDeprecateArtifactVersion={session.deprecateArtifactVersion}
        onValidateArtifactVersion={session.validateArtifactVersion}
        onDisposeArtifactVersion={session.disposeArtifactVersion}
        onRegisterArtifactDependency={session.registerArtifactDependency}
        onRemoveArtifactDependency={session.removeArtifactDependency}
        onValidateArtifactDependencies={session.validateArtifactDependencies}
        onDisposeArtifactDependency={session.disposeArtifactDependency}
        onBuildPublicationPlan={session.buildPublicationPlan}
        onValidatePublicationPlan={session.validatePublicationPlan}
        onPublishPublicationPlan={session.publishPublicationPlan}
        onDisposePublicationPlan={session.disposePublicationPlan}
        onStartPublicationExecution={session.startPublicationExecution}
        onExecutePublicationStep={session.executePublicationStep}
        onCompletePublicationExecution={session.completePublicationExecution}
        onValidatePublicationExecution={session.validatePublicationExecution}
        onDisposePublicationExecution={session.disposePublicationExecution}
        onBuildArtifactExport={session.buildArtifactExport}
        onValidateArtifactExport={session.validateArtifactExport}
        onExportArtifact={session.exportArtifact}
        onDisposeArtifactExport={session.disposeArtifactExport}
      />
    </AppShell>
  );
}
