/**
 * @embed-engine/runtime — Runtime packages (Priority Journey + Decision Session).
 */

export {
  applyPriorityEvent,
  createInitialPriorityRuntimeState,
  createPriorityRuntimeEngine,
  hasConfirmedSelection,
  hasExperience,
  hasHouseMapping,
  isPriorityJourneyComplete,
  isSelectionNonEmpty,
  resetPriorityRuntimeState,
  type ApplyPriorityEventFailure,
  type ApplyPriorityEventResult,
  type ApplyPriorityEventSuccess,
  type PriorityEngineEvent,
  type PriorityEngineEventType,
  type PriorityRuntimeEngine,
  type PriorityRuntimeState,
  type PriorityTransitionError,
  type PriorityTransitionErrorCode,
} from "./priority";

export {
  GARDEN_OBJECT_ID,
  GARDEN_PRIORITY_ID,
  GARDEN_PRIMARY_FOLLOWUP_TARGET_ID,
  createGardenEngineEvents,
  createGardenJourneyRun,
  gardenContentPackage,
  gardenExperience,
  gardenFollowUps,
  gardenHouseMapping,
  gardenInterpretation,
  gardenPrioritySelection,
  gardenTransitionMessage,
} from "./priority/mock";

export {
  renderPriorityJourney,
  type PriorityRenderModel,
} from "./priority/html-renderer";

export {
  DECISION_SESSION_FORMAT,
  DECISION_SESSION_SCHEMA_VERSION,
  DecisionSessionRuntime,
  applyDecisionEvent,
  cloneDecisionSession,
  commandToEvent,
  createDecisionSession,
  createDecisionSessionRuntime,
  createInitialSessionRuntimeState,
  createInterpretationContext,
  createInterpretationRuleset,
  DEFAULT_HOUSE_INTERPRETATION_RULES,
  dispatchCommand,
  evaluateInterpretationRules,
  freezeDecisionSession,
  interpretDecisionSession,
  projectDecisionSession,
  projectExperienceContext,
  projectFromInterpretation,
  replayDecisionSession,
  restoreDecisionSession,
  restoreDecisionSessionFromJson,
  selectRoom,
  serializeDecisionSession,
  serializeDecisionSessionToJson,
  validateCommand,
  type CreateDecisionSessionInput,
  type DecisionEvent,
  type DecisionEventType,
  type DecisionSession,
  type DecisionSessionRuntimeOptions,
  type DispatchCommandInput,
  type DispatchFailure,
  type DispatchResult,
  type DispatchSuccess,
  type ExperienceActiveRoomContext,
  type ExperienceContext,
  type ExperienceDecisionContext,
  type ExperienceNavigationContext,
  type ExperienceObjectContext,
  type FocusRoom,
  type InterpretationContext,
  type InterpretationRule,
  type InterpretationRuleset,
  type InterpretedSemantics,
  type ObjectId,
  type PipelineError,
  type PipelineErrorCode,
  type ProjectSessionResult,
  type RecommendedMediaRef,
  type RecommendedMediaRole,
  type ReplaySessionResult,
  type RestoreSessionResult,
  type RoomId,
  type RuntimeCommand,
  type RuntimeCommandType,
  type SelectRoomFailure,
  type SelectRoomInput,
  type SelectRoomResult,
  type SelectRoomSuccess,
  type SerializeSessionResult,
  type SerializedDecisionSession,
  type SessionExperience,
  type SessionInterpretation,
  type SessionRuntimeState,
  type Timestamp,
  type ValidationResult,
} from "./session";
