/**
 * @embed-engine/runtime — Runtime packages (Priority Journey + Decision Session).
 */

export {
  applyPriorityEvent,
  createInitialPriorityRuntimeState,
  createPriorityRuntimeEngine,
  hasConfirmedSelection,
  hasExperience,
  hasHouseMapping,
  isPriorityJourneyComplete,
  isSelectionNonEmpty,
  resetPriorityRuntimeState,
  type ApplyPriorityEventFailure,
  type ApplyPriorityEventResult,
  type ApplyPriorityEventSuccess,
  type PriorityEngineEvent,
  type PriorityEngineEventType,
  type PriorityRuntimeEngine,
  type PriorityRuntimeState,
  type PriorityTransitionError,
  type PriorityTransitionErrorCode,
} from "./priority";

export {
  GARDEN_OBJECT_ID,
  GARDEN_PRIORITY_ID,
  GARDEN_PRIMARY_FOLLOWUP_TARGET_ID,
  createGardenEngineEvents,
  createGardenJourneyRun,
  gardenContentPackage,
  gardenExperience,
  gardenFollowUps,
  gardenHouseMapping,
  gardenInterpretation,
  gardenPrioritySelection,
  gardenTransitionMessage,
} from "./priority/mock";

export {
  renderPriorityJourney,
  type PriorityRenderModel,
} from "./priority/html-renderer";

export {
  DECISION_SESSION_FORMAT,
  DECISION_SESSION_SCHEMA_VERSION,
  DECISION_STORY_SCHEMA_VERSION,
  DecisionSessionRuntime,
  applyDecisionEvent,
  cloneDecisionSession,
  commandToEvent,
  composeDecisionStory,
  createDecisionSession,
  createDecisionSessionRuntime,
  createInitialSessionRuntimeState,
  createInterpretationContext,
  createInterpretationRuleset,
  createPriorityProfile,
  DEFAULT_HOUSE_INTERPRETATION_RULES,
  dispatchCommand,
  evaluateDecisionFocus,
  evaluateInterpretationRules,
  evaluatePrioritySignals,
  evaluatePrioritySignalsFromIds,
  freezeDecisionSession,
  interpretDecisionSession,
  orderHighlightsByDecisionFocus,
  orderMediaByDecisionFocus,
  projectDecisionSession,
  projectExperienceContext,
  projectFromInterpretation,
  PRIORITY_SIGNAL_KIND_BY_ID,
  replayDecisionSession,
  resolvePrioritySignalKind,
  restoreDecisionSession,
  restoreDecisionSessionFromJson,
  selectRoom,
  serializeDecisionSession,
  serializeDecisionSessionToJson,
  validateCommand,
  type ComposeDecisionStoryInput,
  type CreateDecisionSessionInput,
  type DecisionEvent,
  type DecisionEventType,
  type DecisionFocus,
  type DecisionSession,
  type DecisionSessionRuntimeOptions,
  type DecisionStory,
  type DecisionStoryChapter,
  type DecisionStoryChapterKind,
  type DecisionStoryContract,
  type DecisionStoryProvenance,
  type DispatchCommandInput,
  type DispatchFailure,
  type DispatchResult,
  type DispatchSuccess,
  type ExperienceActiveRoomContext,
  type ExperienceContext,
  type ExperienceDecisionContext,
  type ExperienceNavigationContext,
  type ExperienceObjectContext,
  type FocusRoom,
  type InterpretationContext,
  type InterpretationRule,
  type InterpretationRuleset,
  type InterpretedSemantics,
  type ObjectId,
  type PipelineError,
  type PipelineErrorCode,
  type PriorityId,
  type PriorityProfile,
  type PrioritySignal,
  type PrioritySignalKind,
  type ProjectSessionResult,
  type RecommendedMediaRef,
  type RecommendedMediaRole,
  type ReplaySessionResult,
  type RestoreSessionResult,
  type RoomId,
  type RuntimeCommand,
  type RuntimeCommandType,
  type SelectRoomFailure,
  type SelectRoomInput,
  type SelectRoomResult,
  type SelectRoomSuccess,
  type SerializeSessionResult,
  type SerializedDecisionSession,
  type SessionExperience,
  type SessionInterpretation,
  type SessionRuntimeState,
  type Timestamp,
  type ValidationResult,
} from "./session";
