import assert from "node:assert/strict";
import { describe, it } from "node:test";

import {
  INTERPRETATION_TRACE_FORBIDDEN_PRESENTATION_KEYS,
  createInterpretationTrace,
} from "./InterpretationTrace";
import { interpretationEngine } from "./InterpretationEngine";

describe("InterpretationTrace", () => {
  it("is generated by InterpretationEngine", () => {
    const interpretation = interpretationEngine.interpret({
      objectId: "house-modern-01",
      priorityIds: ["layout"],
    });

    assert.ok(interpretation.trace);
    assert.equal(
      interpretation.trace?.interpretationId,
      interpretation.id,
    );
    assert.equal(interpretation.trace?.objectId, "house-modern-01");
    assert.equal(interpretation.trace?.metadata.producer, "InterpretationEngine");
    assert.equal(interpretation.trace?.metadata.schemaVersion, 1);
    assert.equal(interpretation.trace?.metadata.lensKey, "family");
    assert.ok(interpretation.trace?.modules.includes("strengths"));
    assert.ok(interpretation.trace?.modules.includes("confidence"));
    assert.ok(
      interpretation.trace?.contributions.some(
        (item) => item.kind === "strength" && item.id === "s.bedrooms",
      ),
    );
    assert.ok(
      interpretation.trace?.contributions.some(
        (item) =>
          item.kind === "confidence" &&
          item.confidenceFactors.includes("matchScore:92"),
      ),
    );
  });

  it("is deterministic for identical inputs", () => {
    const a = interpretationEngine.interpret({
      objectId: "house-modern-01",
      priorityIds: ["investment"],
    });
    const b = interpretationEngine.interpret({
      objectId: "house-modern-01",
      priorityIds: ["investment"],
    });
    assert.deepEqual(a.trace, b.trace);
  });

  it("varies by lens while remaining renderer-independent", () => {
    const layout = interpretationEngine.interpret({
      objectId: "house-modern-01",
      priorityIds: ["layout"],
    });
    const baseline = interpretationEngine.interpret({
      objectId: "house-modern-01",
      priorityIds: [],
    });

    assert.notDeepEqual(layout.trace, baseline.trace);
    assert.equal(baseline.trace?.metadata.lensKey, "baseline");

    const keys = Object.keys(layout.trace ?? {});
    for (const forbidden of INTERPRETATION_TRACE_FORBIDDEN_PRESENTATION_KEYS) {
      assert.equal(keys.includes(forbidden), false);
    }

    for (const contribution of layout.trace?.contributions ?? []) {
      const contributionKeys = Object.keys(contribution);
      for (const forbidden of INTERPRETATION_TRACE_FORBIDDEN_PRESENTATION_KEYS) {
        assert.equal(contributionKeys.includes(forbidden), false);
      }
    }
  });

  it("createInterpretationTrace freezes the payload", () => {
    const trace = createInterpretationTrace({
      interpretationId: "interpretation.test.baseline",
      objectId: "test",
      modules: ["lens"],
      contributions: [
        {
          id: "lens.baseline",
          kind: "lens",
          module: "lens",
          inputs: [],
          evidence: ["lens:none"],
          confidenceFactors: [],
        },
      ],
      metadata: {
        producer: "InterpretationEngine",
        schemaVersion: 1,
        lensKey: "baseline",
      },
    });

    assert.ok(Object.isFrozen(trace));
    assert.ok(Object.isFrozen(trace.modules));
    assert.ok(Object.isFrozen(trace.contributions));
    assert.ok(Object.isFrozen(trace.contributions[0]));
    assert.ok(Object.isFrozen(trace.metadata));
  });
});
