import assert from "node:assert/strict";
import { describe, it } from "node:test";

import {
  INTERPRETATION_TRACE_FORBIDDEN_PRESENTATION_KEYS,
  createInterpretationTrace,
} from "./InterpretationTrace";
import { createDecisionContext } from "./DecisionContext";
import { interpretationEngine } from "./InterpretationEngine";
import { getSemanticRuleById } from "./rules/semanticRuleCatalog";

function interpret(objectId: string, priorityIds: readonly string[]) {
  return interpretationEngine.interpret({
    object: { id: objectId },
    context: createDecisionContext({ priorities: { selected: priorityIds } }),
  });
}

describe("InterpretationTrace", () => {
  it("is generated by InterpretationEngine", () => {
    const interpretation = interpret("house-modern-01", ["layout"]);

    assert.ok(interpretation.trace);
    assert.equal(
      interpretation.trace?.interpretationId,
      interpretation.id,
    );
    assert.equal(interpretation.trace?.objectId, "house-modern-01");
    assert.equal(interpretation.trace?.metadata.producer, "InterpretationEngine");
    assert.equal(interpretation.trace?.metadata.schemaVersion, 1);
    assert.equal(interpretation.trace?.metadata.lensKey, "family");
    assert.ok(interpretation.trace?.modules.includes("strengths"));
    assert.ok(interpretation.trace?.modules.includes("confidence"));
    assert.ok(
      interpretation.trace?.contributions.some(
        (item) => item.kind === "strength" && item.id === "s.bedrooms",
      ),
    );
    assert.ok(
      interpretation.trace?.contributions.some(
        (item) =>
          item.kind === "confidence" &&
          item.confidenceFactors.includes("matchScore:92"),
      ),
    );
  });

  it("references canonical SemanticRuleContract identities", () => {
    const interpretation = interpret("house-modern-01", ["layout"]);

    const strength = interpretation.trace?.contributions.find(
      (item) => item.id === "s.bedrooms",
    );
    assert.equal(strength?.ruleId, "LAYOUT_001");
    assert.equal(getSemanticRuleById("LAYOUT_001")?.meaning, "family.bedrooms");

    const lens = interpretation.trace?.contributions.find(
      (item) => item.kind === "lens",
    );
    assert.equal(lens?.ruleId, "LENS_001");

    const intent = interpretation.trace?.contributions.find(
      (item) => item.kind === "intent",
    );
    assert.equal(intent?.ruleId, "INTENT_001");

    for (const contribution of interpretation.trace?.contributions ?? []) {
      assert.ok(contribution.ruleId);
      assert.ok(getSemanticRuleById(contribution.ruleId));
    }

    // Interpretation semantic outputs remain code-based (unchanged).
    assert.equal(interpretation.strengths[0]?.code, "family.bedrooms");
    assert.equal(interpretation.matchScore, 92);
  });

  it("is deterministic for identical inputs", () => {
    const a = interpret("house-modern-01", ["investment"]);
    const b = interpret("house-modern-01", ["investment"]);
    assert.deepEqual(a.trace, b.trace);
    assert.equal(
      a.trace?.contributions.find((item) => item.id === "f.price")?.ruleId,
      "PRICE_001",
    );
  });

  it("varies by lens while remaining renderer-independent", () => {
    const layout = interpret("house-modern-01", ["layout"]);
    const baseline = interpret("house-modern-01", []);

    assert.notDeepEqual(layout.trace, baseline.trace);
    assert.equal(baseline.trace?.metadata.lensKey, "baseline");
    assert.equal(
      baseline.trace?.contributions.find((item) => item.kind === "lens")?.ruleId,
      "LENS_005",
    );

    const keys = Object.keys(layout.trace ?? {});
    for (const forbidden of INTERPRETATION_TRACE_FORBIDDEN_PRESENTATION_KEYS) {
      assert.equal(keys.includes(forbidden), false);
    }

    for (const contribution of layout.trace?.contributions ?? []) {
      const contributionKeys = Object.keys(contribution);
      for (const forbidden of INTERPRETATION_TRACE_FORBIDDEN_PRESENTATION_KEYS) {
        assert.equal(contributionKeys.includes(forbidden), false);
      }
    }
  });

  it("createInterpretationTrace freezes the payload", () => {
    const trace = createInterpretationTrace({
      interpretationId: "interpretation.test.baseline",
      objectId: "test",
      modules: ["lens"],
      contributions: [
        {
          id: "lens.baseline",
          kind: "lens",
          module: "lens",
          ruleId: "LENS_005",
          inputs: [],
          evidence: ["lens:none"],
          confidenceFactors: [],
        },
      ],
      metadata: {
        producer: "InterpretationEngine",
        schemaVersion: 1,
        lensKey: "baseline",
      },
    });

    assert.ok(Object.isFrozen(trace));
    assert.ok(Object.isFrozen(trace.modules));
    assert.ok(Object.isFrozen(trace.contributions));
    assert.ok(Object.isFrozen(trace.contributions[0]));
    assert.ok(Object.isFrozen(trace.metadata));
    assert.equal(trace.contributions[0]?.ruleId, "LENS_005");
  });
});
