import { KNOWLEDGE_V04, FAQ_V04 } from './modern4kkKnowledgeV04';
/** CAP-REF-05 — Normalized source-backed MODERN 4KK Priority FAQ. */
import type { HouseKnowledgeAtom } from '../knowledge/houseKnowledgeTypes';
import type { HousePriorityFaqItem } from '../priority-faq/housePriorityFaqTypes';
import type { HouseSpecification } from '../specification/houseSpecificationTypes';

export const MODERN_4KK_SPECIFICATION: HouseSpecification = {
  identity: {
    houseId: 'modern-4kk',
    name: 'MODERN 4KK',
    slug: 'modern-4kk',
    objectType: 'bungalow',
    canonicalProjectId: 'project-domy-s-energii',
    companyId: 'company-domy-s-energii',
    status: 'published',
    role: 'reference',
  },
  dimensions: { usableAreaM2: 112.9, builtUpAreaM2: 129, storeys: 1 },
  disposition: { layoutCode: '4+KK', bathrooms: 1 },
  construction: {
    constructionSystem: 'Lehký dřevěný rámový systém z KVH',
    structure: 'Příčné dřevěné rámy se spojitým pětikloubovým statickým systémem',
    roofType: 'Šikmá střecha',
  },
  energy: {
    energyClass: 'A',
    heatingDemand: 'Tepelná ztráta přibližně 3,7 kW',
    renewables: ['Fotovoltaika'],
    insulationSummary: 'Ekopanel, Climatizer Plus a difuzně otevřený odvětrávaný plášť',
  },
  technologies: {
    hvac: ['ZEHNDER: větrání, vytápění a chlazení', 'Záložní elektrické topné fólie'],
    ventilation: 'Řízené mechanické větrání s rekuperací',
    smartHome: ['AMPIO'],
    water: 'Bojler s integrovaným tepelným čerpadlem a AKIRETHERM 80',
  },
  materials: {
    primaryMaterials: ['KVH', 'Ekopanel', 'Climatizer Plus'],
    facade: 'Antracitový plech a vybrané části z přírodního dřeva',
    interiorFinishesStandard: 'Třívrstvá dubová dřevěná podlaha 14 mm; laminovaná DTD v dekoru bělený dub',
  },
  limitations: {
    limitations: [
      'Konkrétní roční energetické náklady, úspory a návratnosti vyžadují vstupy konkrétní domácnosti.',
      'Konkrétní požární odolnost vyžaduje PBŘ, certifikaci nebo klasifikační protokol.',
      'Parametry realizace v Ostravě–Krásném Poli nejsou automaticky vlastnostmi typového domu.',
    ],
  },
};

const CURRENT_SOURCE = {
  sourceId: 'conis-dse-4kk-knowledge-base-v1',
  kind: 'CURRENT_CONFIRMED' as const,
  label: 'Konsolidovaná Knowledge Base DSE 4KK v1',
};

const LEGACY_KNOWLEDGE: readonly HouseKnowledgeAtom[] = [
  {
    id: 'product-optimized-house',
    houseId: 'modern-4kk',
    subject: 'Vyladěný dům před pozemkem a klientem',
    category: 'product-philosophy',
    statement: 'MODERN 4KK je předem optimalizovaný celek; vhodnost se ověřuje vůči konkrétnímu pozemku a způsobu života.',
    scope: 'PRODUCT', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: ['Není určen pro neomezenou individualizaci.'],
    safeInterpretation: 'Při rozhodování má smysl porovnat pevné vlastnosti domu s konkrétním místem a způsobem života.',
    unsupportedConclusions: ['Výběr priority sám o sobě neznamená zájem o individuální konfiguraci domu.'],
    relatedTopics: ['pozemek', 'flexibilita'],
  },
  {
    id: 'product-space-efficiency',
    houseId: 'modern-4kk', subject: 'Malý zvenčí, velký uvnitř', category: 'space-efficiency',
    statement: 'Kompaktní dispozice omezuje chodby a nevyužité plochy; otevřený obytný prostor vytváří větší vnímaný objem.',
    scope: 'PRODUCT', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: [],
    safeInterpretation: 'V běžném používání se důraz přesouvá k plochám a objemu, které obyvatelé skutečně využívají.',
    factPoint: 'MÉNĚ PLOCHY PADNE NA CHODBY.',
    interpretationPoint: 'VÍCE PLOCHY ZŮSTÁVÁ PRO ŽIVOT.',
    relatedTopics: ['dispozice', 'design'],
  },
  {
    id: 'product-garden-living',
    houseId: 'modern-4kk', subject: 'Byt v zahradě', category: 'garden-relationship',
    statement: 'Obytné místnosti mají přímý vztah k exteriéru; jižní krytá terasa propojuje kuchyň, pracovnu a dětský pokoj se zahradou.',
    scope: 'PRODUCT', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: ['Vhodnost orientace vždy závisí na konkrétní parcele.'],
    safeInterpretation: 'Kontakt se zahradou lze posuzovat jako součást každodenního využití hlavních obytných místností.',
    relatedTopics: ['pozemek', 'dispozice', 'soukromí'],
  },
  {
    id: 'product-layout-structure',
    houseId: 'modern-4kk', subject: 'Dispoziční svoboda', category: 'layout',
    statement: 'Hlavní nosný systém je soustředěn do příčných rámů, takže vnitřní dispozice neobsahuje nosné stěny.',
    scope: 'PRODUCT', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: ['Rozsáhlé změny dispozice mohou narušit původní optimalizaci.'],
    safeInterpretation: 'Případné změny je vhodné hodnotit vůči původní optimalizaci domu, nikoli jako automaticky vhodné.',
    unsupportedConclusions: ['Priorita Dispozice ani Design neznamená automatický požadavek na konfigurátor nebo rozsáhlou změnu návrhu.'],
    relatedTopics: ['flexibilita', 'konstrukce'],
  },
  {
    id: 'product-technical-attic',
    houseId: 'modern-4kk', subject: 'Technické podkroví', category: 'storage',
    statement: 'Technické podkroví nad střední částí domu je přístupné stahovacími schůdky a poskytuje rezervní úložnou kapacitu.',
    scope: 'PRODUCT', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: ['Není obytným druhým podlažím.'],
    safeInterpretation: 'Méně často používané věci mohou mít vyhrazené zázemí mimo každodenní obytný provoz.',
    factPoint: 'TECHNICKÉ PODKROVÍ PŘIDÁVÁ ÚLOŽNÝ PROSTOR.',
    interpretationPoint: 'VĚCI NEJSOU V OBYTNÝCH MÍSTNOSTECH.',
    relatedTopics: ['dispozice', 'údržba'],
  },
  {
    id: 'product-construction-system',
    houseId: 'modern-4kk', subject: 'Konstrukční systém', category: 'construction',
    statement: 'Dům používá příčné dřevěné KVH rámy a vnitřní statickou krabici z Ekopanelů pro podélné zavětrování.',
    scope: 'PRODUCT', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: ['Detailní únosnosti a spojovací prostředky nejsou bez projektové dokumentace určeny pro poradenské tvrzení.'],
    safeInterpretation: 'Kvalita vychází ze souhry konstrukce a detailu.',
    factPoint: 'DŘEVĚNÉ RÁMY A EKOPANELY TVOŘÍ NOSNÝ SYSTÉM.',
    interpretationPoint: 'KONSTRUKCE A DETAIL TVOŘÍ JEDEN CELEK.',
    relatedTopics: ['kvalita', 'akustika'],
  },
  {
    id: 'modern-4kk-roof-bratex-click',
    houseId: 'modern-4kk',
    subject: 'roof.covering',
    category: 'architecture',
    statement:
      'Šikmá střecha je opatřena antracitovou plechovou krytinou BRATEX CLICK.',
    scope: 'PRODUCT',
    confidence: 'CONFIRMED',
    source: {
      sourceId: 'owner-confirmation-2026-09-07-roof',
      kind: 'CURRENT_CONFIRMED',
      label: 'Potvrzení vlastníka a vizualizace 01–03',
    },
    validFrom: '2026-09-07',
    temporalStatus: 'CURRENT',
    constraints: [
      'Přesný číselný odstín RAL není v potvrzení uveden.',
      'Technické vlastnosti střechy se čerpají z technické zprávy, nikoli z vizualizace.',
    ],
    unsupportedConclusions: [
      'Konkrétní číselný odstín RAL.',
      'Technické parametry, které nejsou doloženy technickou zprávou.',
    ],
    relatedTopics: ['design', 'materials', 'durability'],
  },
  {
    id: 'modern-4kk-architectural-form',
    houseId: 'modern-4kk',
    subject: 'architecture.form',
    category: 'architecture',
    statement:
      'Dům je navržen jako jednopodlažní podlouhlý bungalov se sedlovou střechou a výrazně proskleným štítem obytné části.',
    scope: 'PRODUCT',
    confidence: 'DOCUMENTED',
    source: {
      sourceId: 'modern-4kk-visual-exterior-v1',
      kind: 'PRODUCT_DOCUMENTATION',
      label: 'Architektonické vizualizace 01–03 a půdorys p1',
    },
    validFrom: '2026-09-07',
    temporalStatus: 'CURRENT',
    constraints: [
      'Jde o popis aktuálního návrhu doloženého vizualizacemi a půdorysem.',
    ],
    unsupportedConclusions: [
      'Přesné rozměry nebo výměry bez ověření projektové dokumentace.',
      'Potvrzení skutečného provedení stavby.',
    ],
    relatedTopics: ['design', 'layout'],
  },
  {
    id: 'modern-4kk-garden-glazing',
    houseId: 'modern-4kk',
    subject: 'openings.gardenGlazing',
    category: 'architecture',
    statement:
      'Obytná část i vybrané pokoje mají velké prosklené plochy v antracitových rámech orientované k terasám a zahradě.',
    scope: 'PRODUCT',
    confidence: 'DOCUMENTED',
    source: {
      sourceId: 'modern-4kk-visual-glazing-v1',
      kind: 'PRODUCT_DOCUMENTATION',
      label: 'Vizualizace 01, 11–12, 15–16 a 19–22',
    },
    validFrom: '2026-09-07',
    temporalStatus: 'CURRENT',
    constraints: [
      'Orientace je popsána vůči terasám a zahradě, nikoli světovým stranám.',
      'Technické parametry oken se čerpají z technické zprávy.',
    ],
    unsupportedConclusions: [
      'Konkrétní světová orientace domu.',
      'Parametry zasklení nebo způsob otevírání bez dokumentace.',
    ],
    relatedTopics: ['design', 'daylight', 'garden'],
  },
  {
    id: 'modern-4kk-anthracite-shading',
    houseId: 'modern-4kk',
    subject: 'openings.externalShading',
    category: 'comfort',
    statement:
      'Prosklené plochy jsou opatřeny antracitovými roletovými žaluziemi.',
    scope: 'PRODUCT',
    confidence: 'CONFIRMED',
    source: {
      sourceId: 'owner-confirmation-2026-09-07-shading',
      kind: 'CURRENT_CONFIRMED',
      label: 'Potvrzení vlastníka a vizualizace 01–03 a 11',
    },
    validFrom: '2026-09-07',
    temporalStatus: 'CURRENT',
    constraints: [
      'Způsob ovládání ani konkrétní typ lamel není v potvrzení uveden.',
    ],
    unsupportedConclusions: [
      'Automatické nebo inteligentní ovládání.',
      'Konkrétní výrobce a model.',
    ],
    relatedTopics: ['comfort', 'summer-comfort', 'privacy'],
  },
  {
    id: 'modern-4kk-wooden-terraces',
    houseId: 'modern-4kk',
    subject: 'exterior.terraces',
    category: 'exterior',
    statement:
      'Na obytné místnosti navazují dřevěné terasy a významná část venkovního pobytového prostoru je zastřešená.',
    scope: 'PRODUCT',
    confidence: 'DOCUMENTED',
    source: {
      sourceId: 'modern-4kk-visual-terraces-v1',
      kind: 'PRODUCT_DOCUMENTATION',
      label: 'Vizualizace 01–03 a 19–22, půdorys p1',
    },
    validFrom: '2026-09-07',
    temporalStatus: 'CURRENT',
    constraints: [
      'Přesný rozsah a rozměry teras musí vycházet z projektové dokumentace.',
    ],
    unsupportedConclusions: [
      'Přesná plocha teras.',
      'Konstrukční skladba zastřešení bez technické dokumentace.',
    ],
    relatedTopics: ['garden', 'design', 'layout'],
  },
  {
    id: 'modern-4kk-two-car-shelter',
    houseId: 'modern-4kk',
    subject: 'exterior.parkingShelter',
    category: 'exterior',
    statement:
      'Součástí návrhu je navazující dřevěný přístřešek se dvěma parkovacími místy.',
    scope: 'PRODUCT',
    confidence: 'DOCUMENTED',
    source: {
      sourceId: 'modern-4kk-visual-carport-v1',
      kind: 'PRODUCT_DOCUMENTATION',
      label: 'Vizualizace 02–03 a půdorys p1',
    },
    validFrom: '2026-09-07',
    temporalStatus: 'CURRENT',
    constraints: [
      'Kapacita dvou míst vychází ze zobrazeného návrhu.',
    ],
    unsupportedConclusions: [
      'Přesné rozměry přístřešku.',
      'Konstrukční nebo statické parametry.',
    ],
    relatedTopics: ['layout', 'parking', 'exterior'],
  },
  {
    id: 'modern-4kk-layout-4kk',
    houseId: 'modern-4kk',
    subject: 'layout.rooms',
    category: 'layout',
    statement:
      'Dispozice 4+kk obsahuje společnou kuchyňskou, jídelní a obývací část, hlavní ložnici a dva další samostatné pokoje.',
    scope: 'PRODUCT',
    confidence: 'DOCUMENTED',
    source: {
      sourceId: 'modern-4kk-floorplan-v1',
      kind: 'PRODUCT_DOCUMENTATION',
      label: 'Půdorys p1 a vizualizace 11–12 a 15–22',
    },
    validFrom: '2026-09-07',
    temporalStatus: 'CURRENT',
    constraints: [
      'Přesné plochy místností musí vycházet z čitelné projektové dokumentace.',
    ],
    unsupportedConclusions: [
      'Přesné výměry jednotlivých místností.',
    ],
    relatedTopics: ['layout', 'family-living'],
  },
  {
    id: 'modern-4kk-secondary-room-use',
    houseId: 'modern-4kk',
    subject: 'layout.secondaryRooms',
    category: 'layout',
    statement:
      'Dva samostatné pokoje lze podle zobrazených variant využít pro spaní, dětský pokoj nebo domácí pracovnu.',
    scope: 'PRODUCT',
    confidence: 'DOCUMENTED',
    source: {
      sourceId: 'modern-4kk-visual-secondary-rooms-v1',
      kind: 'PRODUCT_DOCUMENTATION',
      label: 'Vizualizace 00 a 19–22, půdorys p1',
    },
    validFrom: '2026-09-07',
    temporalStatus: 'CURRENT',
    constraints: [
      'Jde o možné způsoby zařízení samostatných pokojů.',
    ],
    unsupportedConclusions: [
      'Dodávka zobrazeného nábytku nebo pracovního vybavení.',
    ],
    relatedTopics: ['layout', 'flexibility', 'home-office'],
  },
  {
    id: 'modern-4kk-built-in-storage',
    houseId: 'modern-4kk',
    subject: 'layout.storage',
    category: 'layout',
    statement:
      'Návrh počítá s vestavěnými úložnými prostory v chodbě, ložnici a dalších pokojích.',
    scope: 'PRODUCT',
    confidence: 'DOCUMENTED',
    source: {
      sourceId: 'modern-4kk-visual-storage-v1',
      kind: 'PRODUCT_DOCUMENTATION',
      label: 'Vizualizace 00, 13–16, 20 a 22',
    },
    validFrom: '2026-09-07',
    temporalStatus: 'CURRENT',
    constraints: [
      'Rozsah úložných prostor vychází z architektonických vizualizací.',
    ],
    unsupportedConclusions: [
      'Přesný vnitřní objem nebo vybavení skříní.',
    ],
    relatedTopics: ['layout', 'storage'],
  },
  {
    id: 'modern-4kk-kitchen-island',
    houseId: 'modern-4kk',
    subject: 'interior.kitchen',
    category: 'interior',
    statement:
      'Kuchyňská část je navržena s pracovním ostrůvkem a přímo navazuje na jídelní a obývací prostor.',
    scope: 'PRODUCT',
    confidence: 'DOCUMENTED',
    source: {
      sourceId: 'modern-4kk-visual-kitchen-v1',
      kind: 'PRODUCT_DOCUMENTATION',
      label: 'Vizualizace 11–12 a půdorys p1',
    },
    validFrom: '2026-09-07',
    temporalStatus: 'CURRENT',
    constraints: [
      'Konkrétní spotřebiče a rozměry kuchyně nejsou z vizualizace určeny.',
    ],
    unsupportedConclusions: [
      'Konkrétní značky nebo modely spotřebičů.',
      'Přesné rozměry kuchyňské sestavy.',
    ],
    relatedTopics: ['layout', 'family-living', 'interior'],
  },
  {
    id: 'modern-4kk-bathroom-equipment',
    houseId: 'modern-4kk',
    subject: 'interior.bathroom',
    category: 'interior',
    statement:
      'Koupelna je zobrazena se sprchovým koutem s nízkým nebo nezobrazeným prahem, závěsným WC, umyvadlem a oknem.',
    scope: 'PRODUCT',
    confidence: 'DOCUMENTED',
    source: {
      sourceId: 'modern-4kk-visual-bathroom-v1',
      kind: 'PRODUCT_DOCUMENTATION',
      label: 'Vizualizace 17–18',
    },
    validFrom: '2026-09-07',
    temporalStatus: 'CURRENT',
    constraints: [
      'Vizualizace sama nepotvrzuje normovou bezbariérovost.',
    ],
    unsupportedConclusions: [
      'Normová bezbariérovost koupelny.',
      'Konkrétní výrobci a modely sanitárního vybavení.',
    ],
    relatedTopics: ['layout', 'comfort', 'interior'],
  },
  {
    id: 'modern-4kk-interior-palette',
    houseId: 'modern-4kk',
    subject: 'interior.materialPalette',
    category: 'interior',
    statement:
      'Interiér pracuje se světlými stěnami, světlým přírodním dekorem dřeva, antracitovými rámy prosklení a v koupelně s velkoformátovými šedými obklady a černými armaturami.',
    scope: 'PRODUCT',
    confidence: 'DOCUMENTED',
    source: {
      sourceId: 'modern-4kk-visual-interior-v1',
      kind: 'PRODUCT_DOCUMENTATION',
      label: 'Vizualizace 00 a 11–22',
    },
    validFrom: '2026-09-07',
    temporalStatus: 'CURRENT',
    constraints: [
      'Jde o vzhled aktuálního architektonického návrhu.',
      'Přesné materiály se určují podle produktové nebo technické dokumentace.',
    ],
    unsupportedConclusions: [
      'Konkrétní druh dřeva tam, kde není doložen produktovou dokumentací.',
      'Výrobce nebo přesný odstín interiérových prvků.',
    ],
    relatedTopics: ['design', 'materials', 'interior'],
  },
  {
    id: 'product-diffusion-open-envelope',
    houseId: 'modern-4kk', subject: 'Difuzně otevřená obálka', category: 'envelope',
    statement: 'Ekopanel, Climatizer Plus a odvětrávaný plášť tvoří difuzně otevřenou skladbu stěn a šikmin střechy.',
    scope: 'PRODUCT', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: [],
    safeInterpretation: 'Skladba obálky spojuje konstrukční, provozní a dlouhodobé hledisko domu.',
    factPoint: 'STĚNY A STŘECHA MAJÍ DIFUZNĚ OTEVŘENOU SKLADBU.',
    interpretationPoint: 'OBÁLKA SPOJUJE KONSTRUKCI A PROVOZ.',
    relatedTopics: ['konstrukce', 'údržba', 'energie'],
  },
  {
    id: 'product-material-palette',
    houseId: 'modern-4kk', subject: 'Materiálová paleta', category: 'materials',
    statement: 'Exteriér kombinuje antracitový plech, přírodní dřevo ve vybraných částech, antracitová okna a Thermowood borovici na terasách.',
    scope: 'PRODUCT', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: [],
    safeInterpretation: 'Design lze posuzovat přes souhru materiálů, světla a údržby referenčního řešení.',
    factPoint: 'EXTERIÉR KOMBINUJE DŘEVO, PLECH A TERASU.',
    interpretationPoint: 'MATERIÁLY TVOŘÍ JEDNO REFERENČNÍ ŘEŠENÍ.',
    unsupportedConclusions: ['Priorita Design sama o sobě neurčuje estetický vkus návštěvníka ani požadavek na změnu materiálů.'],
    relatedTopics: ['design', 'údržba'],
  },
  {
    id: 'product-maintenance-design',
    houseId: 'modern-4kk', subject: 'Údržba jako součást návrhu', category: 'maintenance',
    statement: 'Snadná údržba vychází z omezeného počtu zákoutí, integrovaného ukládání, hladkých podlah a soustředění technologií.',
    scope: 'PRODUCT', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: ['Dům ani technologie nejsou bezúdržbové; vyžadují předepsané kontroly a servis.'],
    safeInterpretation: 'Každodenní péče může být přehlednější, aniž by se z toho vyvozovala bezúdržbovost domu.',
    factPoint: 'NÁVRH OMEZUJE ZÁKOUTÍ A SOUSTŘEDÍ TECHNOLOGIE.',
    interpretationPoint: 'KAŽDODENNÍ PÉČE JE PŘEHLEDNĚJŠÍ.',
    relatedTopics: ['údržba', 'provoz'],
  },
  {
    id: 'product-private-rooms',
    houseId: 'modern-4kk', subject: 'Soukromí v kompaktním domě', category: 'privacy',
    statement: 'Společenská část je otevřená, zatímco ložnice, dětský pokoj a pracovna zůstávají samostatnými místnostmi.',
    scope: 'PRODUCT', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: ['Číselné akustické parametry vyžadují měření nebo výpočet.'],
    safeInterpretation: 'Společný a soukromý režim domu lze vnímat jako oddělené funkční zóny.',
    factPoint: 'SPOLEČENSKÉ A SOUKROMÉ MÍSTNOSTI JSOU ODDĚLENÉ.',
    interpretationPoint: 'SPOLEČNÝ A SOUKROMÝ REŽIM MÁ SVÉ ZÓNY.',
    relatedTopics: ['soukromí', 'akustika'],
  },
  {
    id: 'dse-integrated-energy',
    houseId: 'modern-4kk', subject: 'Integrovaná energetická strategie', category: 'energy-concept',
    statement: 'DSE propojuje omezení potřeby energie, rekuperaci, účinné zdroje, fotovoltaiku, baterii a časovou optimalizaci.',
    scope: 'DSE_KNOW_HOW', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: ['Není to garance konkrétní energetické nebo finanční úspory.'],
    safeInterpretation: 'Energetiku je vhodné hodnotit jako spolupráci více systémů, nikoli jako výkon jediné technologie.',
    factPoint: 'ENERGETICKÝ KONCEPT SPOJUJE VÍCE SYSTÉMŮ.',
    interpretationPoint: 'ENERGETIKA SE POSUZUJE JAKO CELEK.',
    relatedTopics: ['energie', 'provozní-náklady', 'investice'],
  },
  {
    id: 'dse-energy-cost-guardrail',
    houseId: 'modern-4kk', subject: 'Individuální energetická ekonomika', category: 'guardrail',
    statement: 'Roční náklady, úspory a návratnost energetických technologií závisejí na konfiguraci, užívání, klimatu a cenách.',
    scope: 'DSE_KNOW_HOW', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: ['Bez konkrétních vstupů nelze garantovat účet za energie ani ROI FVE, baterie, AKIRETHERM, elektromobilu nebo Chytrého Spotu.'], relatedTopics: ['provozní-náklady', 'investice'],
  },
  {
    id: 'dse-grid-independence-guardrail',
    houseId: 'modern-4kk', subject: 'Roční bilance není trvalá soběstačnost', category: 'guardrail',
    statement: 'Kladná roční energetická bilance při odpovídající konfiguraci neznamená energetickou soběstačnost v každém okamžiku.',
    scope: 'DSE_KNOW_HOW', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: ['Neslibovat permanentní energetickou soběstačnost.'], relatedTopics: ['energie', 'fotovoltaika'],
  },
  {
    id: 'dse-fire-safety-guardrail',
    houseId: 'modern-4kk', subject: 'Požární bezpečnost', category: 'guardrail',
    statement: 'Požární bezpečnost se vysvětluje přes PBŘ stavby a certifikované vlastnosti materiálů.',
    scope: 'DSE_KNOW_HOW', confidence: 'CONFIRMED', source: CURRENT_SOURCE, validFrom: '2026-08-07', temporalStatus: 'CURRENT',
    constraints: ['Bez protokolu nebo klasifikace neuvádět konkrétní minutové hodnoty požární odolnosti.'], relatedTopics: ['kvalita', 'konstrukce'],
  },
  {
    id: 'dse-information-gaps',
    houseId: 'modern-4kk', subject: 'Hranice doložených informací', category: 'information-gap',
    statement: 'Zdroje nepodporují autonomní detailní odpovědi o aktuální ceně, přesné energetické bilanci, číselné požární a akustické klasifikaci, statických únosnostech ani aktuálních modelech technologií.',
    scope: 'DSE_KNOW_HOW', confidence: 'DOCUMENTED',
    source: { sourceId: 'conis-dse-bungalov-4kk-znalostni-databaze-v1', kind: 'TECHNICAL_DOCUMENTATION', label: 'Znalostní databáze DSE 4KK v1.0' },
    temporalStatus: 'CURRENT',
    constraints: ['Při těchto tématech přiznat hranici znalosti a vyžádat si aktuální podklad.'], relatedTopics: ['cena', 'požár', 'akustika', 'statika', 'technologie'],
  },
  {
    id: 'reference-krasne-pole-realization',
    houseId: 'modern-4kk', subject: 'Ostrava–Krásné Pole', category: 'reference-realization',
    statement: 'Bungalov 4KK byl v roce 2024 realizován v pilotním developerském projektu DSE v Ostravě–Krásném Poli.',
    scope: 'REFERENCE_PROJECT', confidence: 'DOCUMENTED',
    source: { sourceId: 'conis-dse-bungalov-4kk-znalostni-databaze-v1', kind: 'REFERENCE_EVIDENCE', label: 'Znalostní databáze DSE 4KK v1.0' },
    validFrom: '2024-01-01', temporalStatus: 'HISTORICAL',
    constraints: ['Dokládá realizaci konceptu, ne vlastnosti každé budoucí stavby MODERN 4KK.'], relatedTopics: ['reference', 'kvalita'],
  },
  {
    id: 'reference-krasne-pole-boundary',
    houseId: 'modern-4kk', subject: 'Hranice reference Krásné Pole', category: 'reference-guardrail',
    statement: 'Parcely, přípojky, ČOV, vsakování, retence, orientace a infrastruktura Krásného Pole jsou vlastnostmi konkrétní realizace.',
    scope: 'REFERENCE_PROJECT', confidence: 'DOCUMENTED',
    source: { sourceId: 'conis-dse-bungalov-4kk-znalostni-databaze-v1', kind: 'REFERENCE_EVIDENCE', label: 'Znalostní databáze DSE 4KK v1.0' },
    validFrom: '2024-01-01', temporalStatus: 'HISTORICAL',
    constraints: ['Tyto parametry se nesmějí přenášet do House Specification ani tvrdit jako standard typového domu.'], relatedTopics: ['pozemek', 'reference'],
  },
  {
    id: 'historical-atrea-concept',
    houseId: 'modern-4kk', subject: 'Historický koncept ATREA', category: 'technology-history',
    statement: 'Historický návrh pracoval se systémem ATREA, tepelným zásobníkem, zemním kolektorem, Loxone a krbovou vložkou.',
    scope: 'HISTORICAL', confidence: 'DOCUMENTED',
    source: { sourceId: 'conis-dse-bungalov-4kk-znalostni-databaze-v1', kind: 'HISTORICAL', label: 'Znalostní databáze DSE 4KK v1.0' },
    temporalStatus: 'HISTORICAL', constraints: ['Není automaticky současným standardem MODERN 4KK.'], relatedTopics: ['historie', 'energie'],
  },
  {
    id: 'historical-jablotron-concept',
    houseId: 'modern-4kk', subject: 'Historický koncept Jablotron LT', category: 'technology-history',
    statement: 'Historický návrh pracoval s aktivní rekuperací, aktivním bojlerem, Loxone a fotovoltaikou.',
    scope: 'HISTORICAL', confidence: 'DOCUMENTED',
    source: { sourceId: 'conis-dse-bungalov-4kk-znalostni-databaze-v1', kind: 'HISTORICAL', label: 'Znalostní databáze DSE 4KK v1.0' },
    temporalStatus: 'HISTORICAL', constraints: ['Není automaticky současným standardem MODERN 4KK.'], relatedTopics: ['historie', 'energie'],
  },
  {
    id: 'customer-evidence-information-needs',
    houseId: 'modern-4kk', subject: 'Historické rozhodovací evidence', category: 'customer-evidence',
    statement: 'Historická klientská data ukazují zájem o dlouhodobé náklady, retenci vody, technologie a srovnání stavebních řešení.',
    scope: 'CUSTOMER_EVIDENCE', confidence: 'DOCUMENTED',
    source: { sourceId: 'conis-dse-bungalov-4kk-znalostni-databaze-v1', kind: 'HISTORICAL', label: 'Znalostní databáze DSE 4KK v1.0' },
    temporalStatus: 'HISTORICAL', constraints: ['Jde o evidence rozhodovacích témat, nikoli o fyzické vlastnosti domu.'], relatedTopics: ['priorities', 'customer-evidence'],
  },
];

// XLSX 04 is authoritative. Retain visual additions and established payoff IDs,
// but never reintroduce old blanket information-gap claims into current Chat.
const PAYOFF_ROWS: Readonly<Record<string, number>> = {
  'product-space-efficiency': 16,
  'product-garden-living': 28,
  'product-layout-structure': 133,
  'product-private-rooms': 91,
  'product-material-palette': 125,
  'product-construction-system': 263,
  'product-optimized-house': 18,
  'product-technical-attic': 23,
  'dse-integrated-energy': 382,
  'product-diffusion-open-envelope': 264,
  'product-maintenance-design': 96,
};
export const MODERN_4KK_KNOWLEDGE: readonly HouseKnowledgeAtom[] = [
  ...KNOWLEDGE_V04,
  ...LEGACY_KNOWLEDGE.filter(atom => atom.id.startsWith('modern-4kk-')),
  ...LEGACY_KNOWLEDGE.filter(atom => atom.temporalStatus === 'HISTORICAL'),
  ...LEGACY_KNOWLEDGE.filter(atom => atom.id in PAYOFF_ROWS).map(atom => {
    const current = KNOWLEDGE_V04.find(row => row.id === `kb04-row-${PAYOFF_ROWS[atom.id]}`)!;
    return { ...current, id: atom.id, factPoint: atom.factPoint,
      interpretationPoint: atom.interpretationPoint,
      safeInterpretation: current.statement, relatedTopics: atom.relatedTopics,
      unsupportedConclusions: atom.unsupportedConclusions };
  }),
];
export const MODERN_4KK_PRIORITY_FAQ: readonly HousePriorityFaqItem[] = FAQ_V04;
